### ISSUE TITLE
Add link to Application Integration Guide

### ISSUE THREAD

**Issue by Palollo** [asalic/dataset-explorer#100]
It would be interesting to add a new item in the "Documentation" dropdown menú, after the item "API Specs", with the text "Application Integration Guide" or similar, and with the link pointing to:
https://github.com/chaimeleon-eu/workstation-images#how-to-integrate-your-application-in-chaimeleon-platform

**Comment by asalic** [comment]
migrated to https://github.com/chaimeleon-eu/dataset-explorer/issues/99
