### ISSUE TITLE
[Improvement] Add filters in datasets list by flags

### ISSUE THREAD

**Issue by Palollo** [asalic/dataset-explorer#92]
See the API: https://app.swaggerhub.com/apis/UPV-CHAIMELEON/Dataset-service/1.0.0#/datasets/listDatasets
There are filters for the flags _draft_, _public_ and _invalidated_.
Each filter allows to list only datasets with the flag or only those without the flag or both (if the filter is not set).

**Comment by asalic** [comment]
https://github.com/chaimeleon-eu/dataset-explorer/issues/92
